### ISSUE TITLE
Any attempt to continue with this?

### ISSUE THREAD

**Issue by georghildebrand** [gtfierro/brick-ifc-convert#1]
@gtfierro , found this project and wonder if you plan to continue on this or if there is any other project you can recommend about ifc2brick?

**Comment by gtfierro** [comment]
Hi @georghildebrand 

A couple years ago a student developed https://github.com/henriklange/IfcBrickRewrite (documented in [this paper](https://dl.acm.org/doi/abs/10.1145/3276774.3276790)), which should do more than this current package. 

While in principle it should be possible to develop a Brick-to-IFC converter based on just the IFC standard (I think the v4 of the standard has many nice intersections with Brick), I've found it difficult to proceed without real IFC models to test the converter on. The IFC examples I can find online are either from an older version of the standard with even fewer pieces of metadata that Brick can represent, or are too basic/simple to contain any useful metadata for a Brick model. The EXPRESS-to-RDF conversion tools out there seem like a helpful step to build on, but I haven't had the time to dig into understanding the complex data model. The same issue exists with regards to finding examples to test. As a result, I've essentially reached a dead end. I could potentially find some cycles for development, but I'm not sure the right way of going about it, but am definitely open to ideas!

**Comment by georghildebrand** [comment]
@gtfierro , thanks for sharing all these infos! I can confirm your concerns. The lack of realistic data examples remains a problem for the OS community :/.
